server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

trusted-directory:
  issuer-name: SAPI-G Test Trusted Directory
  fqdn: localhost:8080

  signing:
    keystore-type: PKCS12
    key-alias: jwt-signing

  ca:
    keystore-type: PKCS12
    key-alias: ca
    cert-signing-alg: SHA256withRSA

  storage:
    file-path: /var/ttd/trusted-directory-jwks.json

  cert:
    key-size: 2048
    validity-days: 365
