generatorOptions:
  disableNameSuffixHash: true
# For PINGID use only, Docker images are not public - customers will need to provide their own repo name and tag
images:
  - name: testdirectory
    newName:  europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-test-trusted-directory
    newTag:  latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: pingid
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml