---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  config.yml: |
    server:
      port: 8080
    trustedDirectory:
      issuerName: {{ .Values.config.issuerName }}
      fqdn: {{ .Values.config.fqdn }}
      signing:
        keystorePath: {{ .Values.config.signing.keystorePath }}
        keystoreType: {{ .Values.config.signing.keystoreType }}
        keyAlias: {{ .Values.config.signing.keystoreAlias }}
      ca:
        keystorePath: {{ .Values.config.ca.keystorePath }}
        keystoreType: {{ .Values.config.ca.keystoreType }}
        keyAlias: {{ .Values.config.ca.keystoreAlias }}
      storageFilePath: {{ .Values.config.storageFilePath }}