apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  IG_METRICS_USERNAME: {{ .Values.secrets.igMetricsUsername }}
  IG_METRICS_PASSWORD: {{ .Values.secrets.igMetricsPassword }}
  IG_TEST_DIRECTORY_CA_KEYSTORE_KEYPASS: {{ .Values.secrets.igTestDirectoryCAKeystoreKeypass }}
  IG_TEST_DIRECTORY_CA_KEYSTORE_STOREPASS: {{ .Values.secrets.igTestDirectoryCAKeystoreStorepass }}
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_KEYPASS: {{ .Values.secrets.igTestDirectorySigningKeystoreKeypass }}
  IG_TEST_DIRECTORY_SIGNING_KEYSTORE_STOREPASS: {{ .Values.secrets.igTestDirectorySigningKeystoreStorepass }}
