apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  TTD_SIGNING_KEYSTORE_PWD: {{ .Values.config.signing.keystorePwd }}
  TTD_SIGNING_KEYSTORE_KEY_PWD: {{ .Values.config.signing.keystoreKeyPwd }}
  TTD_CA_KEYSTORE_PWD: {{ .Values.config.ca.keystorePwd }}
  TTD_CA_KEYSTORE_KEY_PWD: {{ .Values.config.ca.keystoreKeyPwd }}
