name: Merge - Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  run_merge-template:
    name: Merge - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-merge.yml@main
    secrets: inherit
    with:
      componentName: secure-api-gateway-test-trusted-directory
      dockerTag: $(echo ${{ github.sha }} | cut -c1-7)